export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PRODUCTS_BEGIN = 'PRODUCTS_BEGIN';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';

export const ADD_TO_CART_BEGIN = 'ADD_TO_CART_BEGIN';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_BEGIN = 'REMOVE_FROM_CART_BEGIN';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const PERSONAL_INFO_BEGIN = 'PERSONAL_INFO_BEGIN';
export const PERSONAL_INFO_SUCCESS = 'PERSONAL_INFO_SUCCESS';
export const PERSONAL_INFO_FAILURE = 'PERSONAL_INFO_FAILURE';
